language: node_js

matrix:
  include:
    - os: linux
      env: CC=gcc-4.8 CXX=g++-4.8
      node_js: "7.0"
    - os: osx
      env: CC=clang CXX=clang
      node_js: "7.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
